### ISSUE TITLE
[Question] Does haxe-blockly’s Blockly generate Haxe source code?

### ISSUE THREAD

**Issue by rraallvv** [nickmain/haxe-blockly#1]
Just wondering whether the version of Blockly built from haxe-blockly does generate Haxe source code.
Regards.

**Comment by nickmain** [comment]
haxe-blockly is really just a set of externs and convenience classes for using the Javascript implementation of Blockly. So the existing code-generation hooks are still there.

I personally don't like Blockly's code generation mechanism so I haven't used it. The blocks I am building in Haxe are currently in a proprietary environment and they consist of runtime logic represented by each block that is stitched together. Being Haxe that runtime logic works in JS, Python and C++ as-is, without needing to generate code from the blocks.

I hope to also build some sets of blocks that can be open-source soon. They will follow the same pattern of runtime components that work in different back-end language environments. I also plan to create some blocks that can run in the Haxe macro system to do code generation that way.

Do you have any particular use-cases for code generation ?

**Comment by rraallvv** [comment]
@nickmain,

The code generators in Blockly seem to rely in some kind of introspection that I don’t like. Also I’m trying to avoid having runtime logic because of the overhead with the messaging and queue systems for communication between blocks, it not might seem too much but I’m not sure if it scales well. Also the runtime logic would have to share CPU time with the physics engine and other stuff in the game running on mobile devices.

I’d prefer rather some editor that has blocks like the nodes in an abstract syntax tree. Say something where we could snap together blocks to build a JavaScript AST and then run one of the available tools to convert the JS AST to JavaScript source code. Something like [this](http://jointjs.com/demos/javascript-ast) but editable in the AST side, and with some nodes collapsed into a single one, for instance for the two consecutive “VariableDeclaration” nodes or the nodes with “CallExpresion” and the name of the function.

I’m piking Blockly at the moment but I’m looking forward to find/build something like what I’ve described above that could be used to build not only JS source code but also other popular languages like Lua and C++. That’s where Haxe comes to play.

Regards.
